let orders=[], items=[], products=[], charts=[];
document.addEventListener('DOMContentLoaded',()=>{loadAnalytics(); document.getElementById('refreshBtn')?.addEventListener('click',loadAnalytics);});
async function loadAnalytics(){ await requireAdmin(); const [{data:o},{data:i},{data:p}] = await Promise.all([sb.from('orders').select('*').order('created_at',{ascending:false}).limit(1000), sb.from('order_items').select('*').limit(2000), sb.from('products').select('*')]); orders=o||[]; items=i||[]; products=p||[]; renderKpis(); renderRevenue(); renderStatuses(); renderTopProducts(); renderTopBrands(); }
function clearCharts(){charts.forEach(c=>c.destroy()); charts=[];}
function renderKpis(){ const total=orders.reduce((s,o)=>s+Number(o.total||0),0); document.getElementById('totalRevenue').textContent=fmtMoney(total); document.getElementById('totalOrders').textContent=orders.length; document.getElementById('averageOrder').textContent=fmtMoney(orders.length?total/orders.length:0); document.getElementById('inventoryValue').textContent=fmtMoney(products.reduce((s,p)=>s+(Number(p.price||0)*Number(p.stock||0)),0)); }
function renderRevenue(){ const days=[...Array(30)].map((_,i)=>{const d=new Date(); d.setDate(d.getDate()-(29-i)); return d.toISOString().slice(0,10)}); const vals=days.map(day=>orders.filter(o=>(o.created_at||'').slice(0,10)===day).reduce((s,o)=>s+Number(o.total||0),0)); const c=document.getElementById('analyticsRevenue'); if(window.Chart&&c){charts.push(new Chart(c,{type:'bar',data:{labels:days.map(d=>d.slice(5)),datasets:[{label:'Revenue',data:vals}]},options:{plugins:{legend:{display:false},tooltip:{callbacks:{label:x=>fmtMoney(x.parsed.y)}}},scales:{y:{ticks:{callback:v=>'RWF '+Number(v).toLocaleString()}}}}}));}}
function renderStatuses(){ const map={}; orders.forEach(o=>{const s=o.status||'pending'; map[s]=(map[s]||0)+1}); const c=document.getElementById('statusChart'); if(window.Chart&&c){charts.push(new Chart(c,{type:'doughnut',data:{labels:Object.keys(map),datasets:[{data:Object.values(map)}]},options:{plugins:{legend:{position:'bottom'}}}}));}}
function renderTopProducts(){ const map={}; items.forEach(i=>{const n=i.product_name||'Unknown'; if(!map[n]) map[n]={qty:0,total:0}; map[n].qty+=Number(i.quantity||0); map[n].total+=Number(i.line_total||0);}); const rows=Object.entries(map).sort((a,b)=>b[1].qty-a[1].qty).slice(0,10); document.getElementById('topProducts').innerHTML=rows.map(([n,v])=>`<div class='stat-row'><strong>${n}</strong><span class='right'>${v.qty} sold<br><span class='muted'>${fmtMoney(v.total)}</span></span></div>`).join('')||'<div class="empty compact">No sales yet.</div>';}
function renderTopBrands(){ const map={}; items.forEach(i=>{const n=i.brand||'Unknown'; if(!map[n]) map[n]={qty:0,total:0}; map[n].qty+=Number(i.quantity||0); map[n].total+=Number(i.line_total||0);}); const rows=Object.entries(map).sort((a,b)=>b[1].total-a[1].total).slice(0,10); document.getElementById('topBrands').innerHTML=rows.map(([n,v])=>`<div class='stat-row'><strong>${n}</strong><span class='right'>${v.qty} items<br><span class='muted'>${fmtMoney(v.total)}</span></span></div>`).join('')||'<div class="empty compact">No brand data yet.</div>';}
